# Generated by Django 4.2.7 on 2024-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('decs', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='event_img')),
            ],
        ),
    ]
