# Generated by Django 4.2.7 on 2024-02-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decs',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
