# Generated by Django 4.2.7 on 2024-02-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_app', '0004_rename_decs_event_desc_alter_event_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('Nonveg', 'Nonveg'), ('Beverages', 'Beverages')], default='', max_length=50)),
                ('decs', models.TextField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_img')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
