# Generated by Django 4.2.7 on 2024-02-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_sliderimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
